### ISSUE TITLE
API key entry in the app config for etherscan's Api-Key token.

### ISSUE THREAD

**Issue by ShaunBulbrook** [HeathWallace/ethereum-pos#11]
### Create API key entry in the application configuration for etherscan (https://etherscan.io/apis).
Etherscan rate limits to 5 requests a second. Exceeding this figure will result in the app being blocked.

* Include api key config in app generation/tooling.
* API key should be added as an environment variable to the project.
* An API key itself should not be committed to the repo.
  * Instructions on how to generate and load an api key need to be added to the ReadMe/Wiki

**Comment by dan1elhughes** [comment]
Child of #12.
