### ISSUE TITLE
Identities against individual transactions

### ISSUE THREAD

**Issue by ShaunBulbrook** [HeathWallace/ethereum-pos#14]
### As a user I want to see the skype profile picture and first name of the sender so that I can verify their identity.

Stories: 
- [x] #19 
- [x] #20  
- [x] #21

**Comment by dan1elhughes** [comment]
All three stories are closed, shall we close this one off

**Comment by ShaunBulbrook** [comment]
Tasks have been completed. - Closing this issue.
