### ISSUE TITLE
Create favicon

### ISSUE THREAD

**Issue by morena** [HeathWallace/ethereum-pos#31]
Create a favicon for the project

**Comment by ShaunBulbrook** [comment]
.gitattributes file update seems to have messed up PR #32 which previously fixed this issue.

Reopening. - @morena could you pop the favicon back in?

**Comment by ShaunBulbrook** [comment]
Blocked by #49

**Comment by ShaunBulbrook** [comment]
#49 has now been merged. - Issue is unblocked.
