### ISSUE TITLE
Settings Wheel Component 

### ISSUE THREAD

**Issue by ShaunBulbrook** [HeathWallace/ethereum-pos#34]
## `<SettingsWheel/>`

A button shown in the header to display the settings panel overlay. This should have an icon and accessible text.

For further enhancement an animation on click of the wheel can be added.

This component should be created in Storybook, with designs TBD.

### Output props

- `onClick()`: called when the wheel is clicked

**Comment by dan1elhughes** [comment]
We have this component right? What about it is blocking #36 ?

**Comment by helenlawes** [comment]
The SettingsWheel has not been added to this repo, so cannot be used in #36

**Comment by ShaunBulbrook** [comment]
Will be added tonight. - I'll update #36 when it is complete.
