### ISSUE TITLE
Header component

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#36]
## `<Header/>`

A fixed header bar which renders above the transaction list and contains the settings wheel.

This component should be created in Storybook, with designs TBD.

### Input props

- `theme`: use light or dark background for the header
- `children`: arbitrary content to display within the header

**Comment by helenlawes** [comment]
Integrating settings wheel is blocked by #34

**Comment by ShaunBulbrook** [comment]
#34 has now been closed and this should be unblocked.
