### ISSUE TITLE
TransactionList component

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#38]
## `<TransactionList/>`

Iterates through the transactions and hands rendering responsibility to child `<Transaction/>` components. Should have an empty state for no transactions.

Other possibilities include pagination, infinite scrolling with lazy loading, or filtering by sender.

This component should be created in Storybook, with designs TBD.

### Input props

- `transactions[]`
	- `from`: the address from which the transaction was sent
	- `to`: address from which the transaction was sent
	- `amount`: the amount of currency moved in the transaction
	- `time`: the timestamp at which the transaction occurred
	- `trust`: the number of confirmations that the transaction has received

**Comment by peasandwell** [comment]
I will be taking this ticket.

**Comment by ShaunBulbrook** [comment]
Added in #46
