### ISSUE TITLE
Transaction component

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#39]
## `<Transaction/>`

A visualisation of a particular transaction.

Further enhancement could be tapping the transaction to toggle an expanded view to see more data.

This component should be created in Storybook, with designs TBD.

### Input props

- `from`: the address from which the transaction was sent
- `to`: address from which the transaction was sent
- `amount`: the amount of currency moved in the transaction
- `time`: the timestamp at which the transaction occurred
- `trust`: the number of confirmations that the transaction has received

**Comment by peasandwell** [comment]
I will be taking this ticket.

**Comment by ShaunBulbrook** [comment]
Added in #46
