### ISSUE TITLE
Deploy to publicly accessible URL

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#50]
The app needs to be deployed from `master` into a publicly accessible location. Heroku is being investigated.

**Comment by ShaunBulbrook** [comment]
Recall you sending out a link to a heroku address. - Has this been wrapped?

**Comment by dan1elhughes** [comment]
That address was for the identity resolver API, Heroku has been approved for the org but not deployed yet

**Comment by dan1elhughes** [comment]
Deployed to Heroku with automatic deploys from `master enabled`
