### ISSUE TITLE
Replace Ethplorer API with Etherscan API

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#68]
### Expected behaviour

Ethplorer API works reliably.

### Actual behaviour

Ethplorer API does not work reliably.

### Steps to reproduce behaviour

Wait for the Ethplorer API to go down.

### Proposed fix

Replace the Ethplorer API with the Etherscan API.

Ethplorer API format:
`https://api.ethplorer.io/getAddressHistory/<wallet>/?token=<token>&type=transfer&apiKey=freekey`

Etherscan API format:
`https://api.etherscan.io/api?module=logs&action=getLogs&fromBlock=0&toBlock=latest&topic0=<hashedFunctionSig>&topic2=<paddedDestinationAddress>&apikey=<apiKey>`

- `hashedFunctionSig` and `paddedDestinationAddress` are [described here](https://ethereum.stackexchange.com/questions/12553/understanding-logs-and-log-blooms).

**Comment by dan1elhughes** [comment]
Ethplorer is falling over quite a lot and not returning data to queries on Safari. Bumping the priority of this.

**Comment by ShaunBulbrook** [comment]
Would be quite keen to pair with you on this if you can spare the time?
