### ISSUE TITLE
Setup Jest automated testing

### ISSUE THREAD

**Issue by peasandwell** [HeathWallace/ethereum-pos#81]
We need to set up an automated testing framework on the build, preferably something like [Jest](https://facebook.github.io/jest/) (as that's the current trendy one). Even a basic setup would be better than nothing at this stage.

Essential for completion:
- Jest setup
- Basic example of test-scripted component that can be used as template for other team members

Bonus points (but can be descoped in this task):
- Test scripts for each component (may need this one to be split out into a new task if desired)
- Setup snapshot testing
- Educate others on automated testing (opportunity for dev tutorial)

**Comment by dan1elhughes** [comment]
Relevant articles

- https://github.com/mthuret/storybook-addon-specifications
- https://facebook.github.io/jest/docs/en/tutorial-react.html

**Comment by peasandwell** [comment]
This may be quite a large task because we'd need to add basic test scripts for each of the existing components, but once we get the ball rolling it should be easier.

**Comment by dan1elhughes** [comment]
Is the PR sufficient to close this issue

**Comment by peasandwell** [comment]
@dan1elhughes for the purposes of this task, yes it is sufficient. 

However in future components/reducers we will need to ensure that scripts should be added where required.
