### ISSUE TITLE
No transactions shown in Safari (iPad, MacOS)

### ISSUE THREAD

**Issue by dan1elhughes** [HeathWallace/ethereum-pos#86]
### Expected behaviour

Transactions are shown.

### Actual behaviour

No transactions are shown.

### Steps to reproduce behaviour

Load the app in Safari.

**Comment by ShaunBulbrook** [comment]
Relates to #68

**Comment by dan1elhughes** [comment]
@morena I've merged in the PR for #68, can you re-test the production site?

**Comment by dan1elhughes** [comment]
Fixed in #93
